# -*- coding: utf-8 -*-
"""Write the final texts of Figs. 1, 3 and 4 (deck slides 1, 2, 3) plus the text drawn inside the icon images to
slide_texts.txt, for the banned-term scan.
2 Oct 2026: subscripts of Figs. 3 and 4 included; the deck holds only the three figure slides (no-photo Fig. 1)."""
import os
from pptx import Presentation

import schem_paths as _SP                               # repository paths
DECK = str(_SP.DECK)
OUT = str(_SP.WORK / 'slide_texts.txt')
prs = Presentation(DECK)
FIGS = (('1', 1), ('3', 2), ('4', 3))
# text rendered inside the icon PNGs (make_icons.py, make_icons_geobg.py)
ICON_TEXT = {
    '1': ['(x, y)', 'l', 'x', 'y', 'θ', '0°–180°',                                  # Step 2 sketches
        'Fold 1', 'Fold 2', 'Fold 3', 'Fold 4',                                   # hold-out icon (round 3)
        'Held-out', 'EVAE', 'ADFNE', 'KDE'],                                      # comparison icon
    '3': ['l', '0°', '90°', '180°'],                                                # output icons
    '4': ['0°', '90°', '180°', 'C1', 'C2', 'C3', 'C4', 'U'],                        # loss icons
}
# the three drawn Step 1 icons of Fig. 1 (make_icons_nophoto.py) hold no text


def walk(shapes):
    for sh in shapes:
        if sh.shape_type is not None and 'GROUP' in str(sh.shape_type):
            yield from walk(sh.shapes)
        elif sh.has_text_frame and sh.text_frame.text.strip():
            yield ' / '.join(p.text for p in sh.text_frame.paragraphs if p.text.strip())


out = ['# Final texts of Figs. 1, 3, 4 (deck %s, slides 1, 2, 3), one text box per line; "/" separates lines' % os.path.basename(DECK),
       '# followed by the text drawn inside the icon images. Generated by dump_slide_texts.py.', '']
for fig, sl in FIGS:
    out.append('== Figure %s (slide %d): text boxes' % (fig, sl))
    out += list(walk(prs.slides[sl - 1].shapes))
    out.append('== Figure %s: text inside icon images' % fig)
    out.append(' | '.join(ICON_TEXT[fig]))
    out.append('')
open(OUT, 'w', encoding='utf-8').write('\n'.join(out))
print('\n'.join(out))
